### ISSUE TITLE
#2 기본 형태 정리

### ISSUE THREAD

**Issue by JaeWookLim** [JaeWookLim/ReverseProposal#2]
Assignees 유윤재

Markdown 트리 형태 만들기

**Comment by yj01203** [comment]
이전에 만든 틀은 한 md파일에 모두 정리하느라 가독성이 떨어지고 편집이 힘들어 부득이하게 나누게 되었습니다.

**Comment by yj01203** [comment]
이미지 링크 수정합니다

> src="/Reverse_Proposal/images/파일이름.확장자"

입니다
